Update GitHub Copilot.json
OpenTermsArchive/GenAI-declarations pull request #99
Opened 2023-11-29 08:15 UTC by bricebai1

Changing a brittle selector that broke down with the site update. (The new selector that I've found is not that simple either. I would be happy to learn if there is a simpler one.)

2023-12-13 12:11 UTC, MattiSG reviewed
Thanks @bricebai1! There is indeed a simpler selector, as suggested 🙂 

When inspecting the document, you can see that the node with the legal text has the following `class` attribute: `class="MarkdownContent_markdownBody__v5MYy markdown-body"`.
As the classes are separated by a space, this means that the node has both the `MarkdownContent_markdownBody__v5MYy` and `markdown-body` classes. It is thus more stable to use the second one 🙂 

I will apply this change and proceed with merging.

2023-12-13 12:11 UTC, MattiSG commented on declarations/GitHub Copilot.json
> +            ".ArticleGridLayout_containerBox__lLLio"
```suggestion
            ".markdown-body"
```

2023-12-13 12:11 UTC, MattiSG approved these changes

2023-12-13 12:16 UTC, MattiSG requested changes
Oops, sorry, I was too fast in approving. We need to make sure that the `.markdown-body` was already valid before. If not (or if we don't check that), we should add a [history entry](https://docs.opentermsarchive.org/contributing-terms/#service-history).

2023-12-13 12:17 UTC, MattiSG commented
The history entry can be generated automatically by using the contribution tool.

2024-01-10 11:33 UTC, clementbiron commented
GitHub Copilot Terms of Service is using multipage which is not supported by the contribution tool.

2024-03-15 09:05 UTC, clementbiron approved these changes
It seems that the `.markdown-body` selector has been valid since the [first snapshot](https://github.com/OpenTermsArchive/GenAI-snapshots/commit/7939ce45cda7374137a57f5b48690065296f73d0) was recorded.

2024-03-19 08:40 UTC, merged